# Default route
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Trout routes
trout_demo:
    resource: "@TroutDemoBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type: rest
    resource: Trout\DemoBundle\Controller\UserController

