trout_demo:
    resource: "@TroutDemoBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type: rest
    resource: Trout\DemoBundle\Controller\UserController

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
