# Default route
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# API doc generator
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

#        Profile
trout_demo_profile_all_json:
    pattern:  /profile/all
    defaults: { _controller: TroutDemoBundle:Profile:all, _format: json }
    requirements:
        _method: GET

trout_demo_profile_get:
    pattern:  /profile/get/{id}
    defaults: { _controller: TroutDemoBundle:Profile:get, _format: json}
    requirements:
        _method: GET

trout_demo_profile_add:
    pattern:  /profile/add
    defaults: { _controller: TroutDemoBundle:Profile:add, _format: json}
    requirements:
        _method: POST

trout_demo_profile_edit:
    pattern:  /profile/edit/{id}
    defaults: { _controller: TroutDemoBundle:Profile:edit, _format: json }
    requirements:
        _method: PUT

trout_demo_profile_upload:
    pattern:  /profile/upload/{id}
    defaults: { _controller: TroutDemoBundle:Profile:uploadImage, _format: json}
    requirements:
        _method: POST

trout_demo_profile_delete:
    pattern:  /profile/delete/{id}
    defaults: { _controller: TroutDemoBundle:Profile:delete, _format: json}
    requirements:
        _method: DELETE

#        Job Offer
trout_demo_job_offer_all_json:
    pattern:  /jobOffer/all
    defaults: { _controller: TroutDemoBundle:JobOffer:all, _format: json }
    requirements:
        _method: GET

trout_demo_job_offer_get:
    pattern:  /jobOffer/get/{id}
    defaults: { _controller: TroutDemoBundle:JobOffer:get, _format: json}
    requirements:
        _method: GET

trout_demo_job_offer_add:
    pattern:  /jobOffer/add
    defaults: { _controller: TroutDemoBundle:JobOffer:add, _format: json}
    requirements:
        _method: POST

trout_demo_job_offer_edit:
    pattern:  /jobOffer/edit/{id}
    defaults: { _controller: TroutDemoBundle:JobOffer:edit, _format: json }
    requirements:
        _method: PUT

trout_demo_job_offer_publish:
    pattern:  /jobOffer/publish/{id}
    defaults: { _controller: TroutDemoBundle:JobOffer:publish, _format: json}
    requirements:
        _method: GET

trout_demo_job_offer_close:
    pattern:  /jobOffer/close/{id}
    defaults: { _controller: TroutDemoBundle:JobOffer:close, _format: json}
    requirements:
        _method: GET

trout_demo_job_offer_offer:
    pattern:  /jobOffer/offer/{id}/{profileId}
    defaults: { _controller: TroutDemoBundle:JobOffer:offer, _format: json}
    requirements:
        _method: GET

trout_demo_job_offer_delete:
    pattern:  /jobOffer/delete/{id}
    defaults: { _controller: TroutDemoBundle:JobOffer:delete, _format: json}
    requirements:
        _method: DELETE


